apiVersion: v1
kind: Pod
metadata:
  name: busyboxs
  namespace: default
spec:
  containers:
    - image: registry.cn-hongkong.aliyuncs.com/flatychen/busyboxs
      command:
        - sleep
        - "3600"
      imagePullPolicy: IfNotPresent
      name: busyboxs
  restartPolicy: Always